mode: 0 #mode=0 本机模式，启动后会根据rate设置的时间运行 mode=1 github_action模式，每次启动只运行一次
station_id:  #站点id 通过抓包得到，也可以不填写此字段，只填写下面的经纬度，填写此字段后经纬度的配置不会生效
rate: 3600 #监控频率，单位：秒，GitHub action模式下需要配置monitor.yml，本设置无效
#地理位置信息 填写经纬度之后则不需要填写，站点id，经纬度可以通过https://lbs.amap.com/tools/picker 获取
latitude: 31.179447
longitude: 121.419891
bark:
  id: #bark id 支持多设备
    -
  sound: alarm #通知声音
